// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD14eewpbvuVlfhIvAT2jJukRsS7b7nj7Y',
    appId: '1:1000065873402:web:52cc674d5574723f9d2043',
    messagingSenderId: '1000065873402',
    projectId: 'dyplom-e1468',
    authDomain: 'dyplom-e1468.firebaseapp.com',
    databaseURL: 'https://dyplom-e1468-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dyplom-e1468.appspot.com',
    measurementId: 'G-ZW409X0Y5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQAn14GKTyGBC4c3yestvx32vMqpfAnZc',
    appId: '1:1000065873402:android:15f72f21a4f84aa19d2043',
    messagingSenderId: '1000065873402',
    projectId: 'dyplom-e1468',
    databaseURL: 'https://dyplom-e1468-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dyplom-e1468.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9VZt-QM53GD2HdYSQvlUOpA5xbrI4sl8',
    appId: '1:1000065873402:ios:a8afa37a9d5531709d2043',
    messagingSenderId: '1000065873402',
    projectId: 'dyplom-e1468',
    databaseURL: 'https://dyplom-e1468-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dyplom-e1468.appspot.com',
    iosClientId: '1000065873402-q4koe2tu9f060c42pvhb6b9gif4c4qta.apps.googleusercontent.com',
    iosBundleId: 'com.example.dyplom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9VZt-QM53GD2HdYSQvlUOpA5xbrI4sl8',
    appId: '1:1000065873402:ios:a8afa37a9d5531709d2043',
    messagingSenderId: '1000065873402',
    projectId: 'dyplom-e1468',
    databaseURL: 'https://dyplom-e1468-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dyplom-e1468.appspot.com',
    iosClientId: '1000065873402-q4koe2tu9f060c42pvhb6b9gif4c4qta.apps.googleusercontent.com',
    iosBundleId: 'com.example.dyplom',
  );
}
